# Pull (Pre-Built):
#   $ podman pull ghcr.io/jelmer/janitor/publish:latest
# Build:
#   $ podman build -t ghcr.io/jelmer/janitor/publish:latest -f Dockerfile_publish .
#   $ buildah build -t ghcr.io/jelmer/janitor/publish:latest -f Dockerfile_publish .
# Run:
#   $ podman run --rm --publish 9912:9912 --name janitor-publish ghcr.io/jelmer/janitor/publish:latest
# Troubleshoot:
#   $ podman run -it --rm -p 9912:9912 --entrypoint=/bin/bash ghcr.io/jelmer/janitor/publish:latest
#   $ podman run --interactive --tty --rm --publish 9912:9912 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor ghcr.io/jelmer/janitor/publish:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        g++ \
        gcc \
        libgpgme-dev \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        swig \
       ## Extra packages
        python3-pip \
 && apt-get clean

# Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
COPY ./scripts/ /usr/local/bin/

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp]" \
 && rm -rf /code

EXPOSE 9912

ENTRYPOINT ["python3", "-m", "janitor.publish", "--port=9912", "--listen-address=0.0.0.0"]
