# https://hub.docker.com/_/postgres
FROM docker.io/postgres:latest
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        postgresql-${PG_MAJOR}-debversion \
 && apt-get clean
