# Pull (Pre-Built):
#   $ docker pull ghcr.io/jelmer/janitor/runner:latest
# Build:
#   $ docker build -t ghcr.io/jelmer/janitor/runner:latest -f Dockerfile_runner .
#   $ buildah build -t ghcr.io/jelmer/janitor/runner:latest -f Dockerfile_runner .
# Run:
#   $ docker run --rm --publish 9911:9911 --name janitor-runner --volume $( pwd ):/mnt/janitor ghcr.io/jelmer/janitor/runner:latest --config /mnt/janitor/janitor.conf.example
# Troubleshoot:
#   $ docker run -it --rm -p 9911:9911 --entrypoint=/bin/bash ghcr.io/jelmer/janitor/runner:latest
#   $ docker run --interactive --tty --rm --publish 9911:9911 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor ghcr.io/jelmer/janitor/runner:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        g++ \
        gcc \
        libgpgme-dev \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        swig \
       ## Extra packages
        dpkg-dev \
        git \
        libapt-pkg-dev \
        python3-pip \
 && apt-get clean

# Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
COPY ./scripts/ /usr/local/bin/

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp,runner]" \
 && rm -rf /code

EXPOSE 9911

ENTRYPOINT ["python3", "-m", "janitor.runner", "--port=9911", "--listen-address=0.0.0.0"]
