# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        g++ \
        gcc \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
       ## Extra packages
        dpkg-dev \
        git \
        libapt-pkg-dev \
        python3-gpg \
        python3-pip \
 && apt-get clean

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp,runner]" \
 && rm -rf /code

EXPOSE 9911

EXPOSE 9919

ENTRYPOINT ["janitor-runner", "--port=9911",  "--public-port=9919", "--listen-address=0.0.0.0"]
