FROM ghcr.io/jelmer/janitor/base:latest
MAINTAINER Jelmer Vernooij <jelmer@debian.org>
VOLUME /vcs
EXPOSE 9923
RUN apt update && apt install -y python3-pip git python3-chardet libjs-sphinxdoc && pip3 install klaus && wget http://ftp.de.debian.org/debian/pool/main/a/aiohttp-wsgi/python3-aiohttp-wsgi_0.10.0-1_all.deb && dpkg -i python3*aiohttp-wsgi*.deb
ENTRYPOINT ["python3", "-m", "janitor.vcs_store", "--port=9923", "--listen-address=0.0.0.0"]
