# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        g++ \
        gcc \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
       ## Extra packages
        git \
        python3-gpg \
        python3-pip \
 && apt-get clean

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[git-store,cloud]" \
 && rm -rf /code

VOLUME /git

EXPOSE 9923

ENTRYPOINT ["janitor-git-store", "--port=9923", "--listen-address=0.0.0.0", "--vcs-path=/git"]
