FROM eu.gcr.io/debian-janitor/base
MAINTAINER Jelmer Vernooij <jelmer@debian.org>
EXPOSE 9912
RUN apt update && apt install -y python3-launchpadlib ssh
ENTRYPOINT ["python3", "-m", "janitor.publish", "--port=9912", "--listen-address=0.0.0.0"]
