FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive
COPY . /code
RUN apt update && apt -y install auto-apt-proxy && apt install --no-install-recommends -y autoconf \
	apt-file \
	ssh \
	python3 \
	pristine-tar \
	devscripts \
	python3-pip \
	quilt \
	sbuild \
	autopkgtest \
	debootstrap \
	git-buildpackage \
	pristine-tar \
	lintian \
	perl-doc \
	dpkg \
	gnome-pkg-tools \
	subversion \
	ca-certificates \
	swig \
	libgpgme-dev \
	make \
	cython3 \
	rustc \
	libpython3-dev \
	build-essential \
	cargo \
	debcargo \
	mypy-protobuf \
	protobuf-compiler \
	ca-certificates \
	python3-apt \
	libpcre3-dev \
	python3-gpg \
	libssl-dev \
	pkg-config \
	&& apt clean \
	&& pip3 install --break-system-packages "/code[gcp,debian]" \
	&& make -C /code \
	&& apt-file update

ENV AUTOPKGTEST=/code/autopkgtest-wrapper
EXPOSE 8080
ENTRYPOINT ["python3", "-m", "janitor.worker", "--port=8080", "--listen-address=0.0.0.0"]
