FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update && apt -y install --no-install-recommends auto-apt-proxy && apt -y upgrade && apt satisfy --no-install-recommends -y git cargo rustc libpython3-dev python3-wheel python3-wheel-whl make protobuf-compiler python3-setuptools python3-setuptools-rust ca-certificates python3-pip libgpgme-dev swig rustc cargo gcc mypy-protobuf libpcre3-dev python3-gpg libssl-dev pkg-config libtdb-dev

COPY . /code

VOLUME /git
EXPOSE 9923
RUN apt update && apt install --no-install-recommends -y libjs-sphinxdoc cargo rustc libpython3-dev && pip3 install --break-system-packages "/code[git_web,gcp]" && rm -rf /code
ENTRYPOINT ["python3", "-m", "janitor.git_store", "--port=9923", "--listen-address=0.0.0.0", "--vcs-path=/git"]
