# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

COPY . /code

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        cargo \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        python3-minimal \
 && apt-get clean \
 && cd /code \
 && cargo build --verbose --release -p janitor-worker



# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
#   Not needed as no Python!
#ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Extra packages
        libpython3-dev \
        python3-breezy \
 && apt-get clean

COPY --from=build /code/target/release/janitor-worker /usr/local/bin/janitor-worker

## Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
#   Not needed as no Python!
#COPY ./scripts/ /usr/local/bin/

COPY autopkgtest-wrapper /usr/local/bin/autopkgtest-wrapper

ENV AUTOPKGTEST=/usr/local/bin/autopkgtest-wrapper

EXPOSE 8080

ENTRYPOINT ["/bin/janitor-worker", "--site-port=8080", "--listen-address=0.0.0.0"]
