# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        cargo \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
        python3-minimal \
 && apt-get clean

COPY . /code

RUN cargo build --release --manifest-path /code/mail-filter/Cargo.toml

FROM docker.io/debian:testing-slim

COPY --from=build /code/target/release/janitor-mail-filter /usr/local/bin/janitor-mail-filter

ENTRYPOINT ["janitor-mail-filter"]
