# Pull (Pre-Built):
#   $ podman pull ghcr.io/jelmer/janitor/ognibuild_dep:latest
# Build:
#   $ podman build -t ghcr.io/jelmer/janitor/ognibuild_dep:latest -f Dockerfile_ognibuild_dep .
#   $ buildah build -t ghcr.io/jelmer/janitor/ognibuild_dep:latest -f Dockerfile_ognibuild_dep .
# Run:
#   $ podman run --rm --publish 9934:9934 --name janitor-ognibuild_dep ghcr.io/jelmer/janitor/ognibuild_dep:latest
# Troubleshoot:
#   $ podman run -it --rm -p 9934:9934 --entrypoint=/bin/bash ghcr.io/jelmer/janitor/ognibuild_dep:latest
#   $ podman run --interactive --tty --rm --publish 9934:9934 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor ghcr.io/jelmer/janitor/ognibuild_dep:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS m4
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get satisfy --yes --no-install-recommends \
        apt-file \
        aptitude \
 && apt-get clean \
 && apt-file update \
 && apt-file search /usr/share/aclocal/.*.m4 --regex -l | xargs aptitude -y install



# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get satisfy --yes --no-install-recommends \
        ca-certificates \
        cargo \
        gcc \
        git \
        libc6-dev \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        python3-minimal \
 && apt-get clean \
 && git clone https://github.com/jelmer/ognibuild.git /build/ognibuild/ \
 && cd /build/ognibuild/ \
 && cargo build --verbose --release #-p dep-server



# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
#   Not needed as no Python!
#ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Extra packages
        libpython3-dev \
        python3-breezy \
 && apt-get clean \
 && rm -rf /usr/share/aclocal

## Due to PyPi's gpg v1.10.0 needing libgpgme-dev < 1.18.0-3
#   Not needed as no Python!
#COPY ./scripts/ /usr/local/bin/

COPY --from=m4 /usr/share/aclocal /usr/share/aclocal

COPY --from=build /build/ognibuild/target/release/ /usr/local/bin/

EXPOSE 9934

ENTRYPOINT ["dep-server", "--port=9934", "--listen-address=0.0.0.0"]
