FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt -y update \
 && apt -y install --no-install-recommends \
        auto-apt-proxy \
 && apt -y upgrade \
 && apt satisfy --no-install-recommends -y \
        ca-certificates \
        cargo \
        gcc \
        git \
        libclang-dev \
        libgpgme-dev \
        libpython3-dev \
        libssl-dev \
        libtdb-dev \
        make \
        mypy-protobuf \
        pkg-config \
        protobuf-compiler \
        python3-gpg \
        python3-pip \
        python3-setuptools \
        python3-setuptools-protobuf \
        python3-setuptools-rust \
        python3-wheel \
        python3-wheel-whl \
        rustc \
        swig

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp]" \
 && rm -rf /code

EXPOSE 9920

RUN apt update \
 && apt install -y \
        devscripts \
        diffoscope \
        libjs-jquery \
 && apt clean

ENTRYPOINT ["python3", "-m", "janitor.differ", "--port=9920", "--listen-address=0.0.0.0"]
