# TODO: config
# TODO: service discovery

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages: ./CONTRIBUTING.md
        cargo \
        g++ \
        gcc \
        libpython3-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler \
       ## Extra packages
        libjs-jquery-datatables \
        python3-gpg \
        python3-pip \
        git \
 && apt-get clean

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp,site]" \
 && rm -rf /code

EXPOSE 8080

EXPOSE 8090

ENTRYPOINT ["janitor-site", "--port=8080", "--public-port=8090", "--host=0.0.0.0"]
