FROM debian:sid-slim AS build

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update && apt -y install auto-apt-proxy && apt -y upgrade && apt satisfy --no-install-recommends -y cargo cython3 rustc libpython3-dev make protobuf-compiler mypy-protobuf python3-setuptools python3-setuptools-rust ca-certificates

ADD . /code
RUN make -C /code && make -C /code/breezy

FROM debian:sid-slim
MAINTAINER Jelmer Vernooij <jelmer@debian.org>
ARG DEBIAN_FRONTEND=noninteractive

RUN echo "deb http://incoming.debian.org/debian-buildd/ buildd-unstable main" >> /etc/apt/sources.list.d/incoming.list && apt -y update && apt -y install auto-apt-proxy && apt -y upgrade
RUN apt satisfy --no-install-recommends -y \
	python3 \
	python3-fastbencode \
	git \
	python3-tqdm \
	python3-distro-info \
	python3-patiencediff \
	python3-aiohttp \
	python3-configobj \
	python3-jinja2 \
	"python3-debian (>= 0.1.47)" \
	python3-requirement-parser \
	python3-asyncpg \
	python3-protobuf \
	python3-yaml \
	python3-gpg \
	python3-cffi \
	python3-future \
	python3-cryptography \
	python3-pycparser \
	python3-pip \
	python3-rsa \
	python3-jwt \
	python3-aiofiles \
	python3-chardet \
	python3-urllib3 \
	python3-apt \
	python3-iso8601 \
	python3-pcre \
	python3-aioredis \
	python3-aiozipkin \
	python3-aiohttp-openmetrics \
	python3-apispec python3-webargs \
	python3-typeshed \
	python3-aiohttp-apispec \
	python3-merge3 \
	wget \
	ca-certificates \
	&& pip3 install --upgrade gcloud-aio-storage google-cloud-logging
COPY --from=build /code /code
ENV BRZ_PLUGINS_AT=debian@/code/breezy-debian
ENV PYTHONPATH=/code:/code/breezy:/code/dulwich:/code/debmutate:/code/silver-platter:/code/upstream-ontologist:/code/buildlog-consultant:/code/ognibuild:/code/lintian-brush
