FROM debian:sid
MAINTAINER Jelmer Vernooij <jelmer@debian.org>

RUN apt update && apt -y upgrade && apt install --no-install-recommends -y python3 git python3-distro-info python3-patiencediff python3-aiohttp python3-configobj python3-jinja2 python3-debian python3-requirement-parser python3-asyncpg python3-protobuf protobuf-compiler python3-yaml python3-prometheus-client python3-gpg python3-cffi python3-future python3-cryptography python3-pycparser python3-pip python3-rsa python3-jwt python3-aiofiles python3-chardet python3-urllib3 python3-apt python3-iso8601 && pip3 install gcloud-aio-storage google-cloud-logging git+https://github.com/jelmer/aiozipkin aiohttp-apispec
ENV BRZ_PLUGINS_AT=debian@/code/breezy-debian
ENV PYTHONPATH=/code:/code/breezy:/code/dulwich:/code/lintian-brush:/code/debmutate:/code/silver-platter:/code/upstream-ontologist:/code/buildlog-consultant:/code/ognibuild
ADD . /code
