FROM docker.io/debian:sid-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive
COPY . /code
RUN apt update && apt -y install auto-apt-proxy && apt install --no-install-recommends -y autoconf \
	apt-file \
	ssh \
	python3 \
	python3-lz4 \
	pristine-tar \
	python3-iso8601 \
	python3-backoff \
	python3-tqdm \
	python3-fastbencode \
	python3-urllib3 \
	python3-aiohttp \
	python3-merge3 \
	python3-configobj \
	python3-jinja2 \
	python3-debian \
	python3-asyncpg \
	python3-protobuf \
	python3-yaml \
	python3-debianbts \
	python3-apt \
	python3-distro-info \
	devscripts \
	python3-prometheus-client \
	python3-gpg \
	python3-requirement-parser \
	python3-ruamel.yaml \
	python3-pcre \
	libpython3.10 \
	quilt \
	python3-psycopg2 \
	sbuild \
	autopkgtest \
	python3-iniparse \
	debootstrap \
	python3-bs4 \
	python3-lxml \
	git-buildpackage \
	pristine-tar \
	lintian \
	perl-doc \
	python3-patiencediff \
	python3-tomlkit \
	python3-aiohttp-openmetrics \
	python3-toml \
	python3-pip \
	dpkg \
	python3-semver \
	gnome-pkg-tools \
	python3-tr \
	subversion \
	python3-pcre \
	ca-certificates \
	make \
	cython3 \
	rustc \
	libpython3-dev \
	cargo \
	debcargo \
	mypy-protobuf \
	protobuf-compiler \
	mypy \
	python3-setuptools \
	python3-setuptools-rust \
	ca-certificates \
	&& apt clean \
	&& make -C /code \
	&& pip3 install "/code[gcp]" \
	&& apt-file update

ENV AUTOPKGTEST=/code/autopkgtest-wrapper
EXPOSE 8080
ENTRYPOINT ["python3", "-m", "janitor.worker", "--port=8080", "--listen-address=0.0.0.0"]
