# Pull (Pre-Built):
#   $ podman pull ghcr.io/jelmer/janitor/differ:latest
# Build:
#   $ podman build -t ghcr.io/jelmer/janitor/differ:latest -f Dockerfile_differ .
#   $ buildah build -t ghcr.io/jelmer/janitor/differ:latest -f Dockerfile_differ .
# Run:
#   $ podman run --rm --publish 9920:9920 --name janitor-differ --volume $( pwd ):/mnt/janitor ghcr.io/jelmer/janitor/differ:latest --config /mnt/janitor/janitor.conf.example
# Troubleshoot:
#   $ podman run -it --rm -p 9920:9920 --entrypoint=/bin/bash ghcr.io/jelmer/janitor/differ:latest
#   $ podman run --interactive --tty --rm --publish 9920:9920 --entrypoint=/bin/bash --volume $( pwd ):/mnt/janitor --workdir /mnt/janitor ghcr.io/jelmer/janitor/differ:latest
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# https://hub.docker.com/_/debian
FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

# Enable forward compatibility with newer versions of Python
ENV PYO3_USE_ABI3_FORWARD_COMPATIBILITY="1"

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages
        ca-certificates \
        cargo \
        gcc \
        git \
        libclang-dev \
        libgpgme-dev \
        libpython3-dev \
        libssl-dev \
        libtdb-dev \
        make \
        mypy-protobuf \
        pkg-config \
        protobuf-compiler \
        python3-gpg \
        python3-pip \
        python3-setuptools \
        python3-setuptools-rust \
        python3-wheel \
        python3-wheel-whl \
        rustc \
        swig \
       ## Extra packages
        devscripts \
        diffoscope \
        libjs-jquery \
        python3-setuptools-protobuf \
 && apt-get clean

COPY ./scripts/ /usr/local/bin/

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp]" \
 && rm -rf /code

EXPOSE 9920

ENTRYPOINT ["python3", "-m", "janitor.differ", "--port=9920", "--listen-address=0.0.0.0"]
