ARG BASE_TAG=latest
FROM ghcr.io/jelmer/janitor/base:${BASE_TAG}
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>
VOLUME /git
EXPOSE 9923
RUN apt update && apt install --no-install-recommends -y libjs-sphinxdoc rustc && pip3 install "/code[git]"
ENTRYPOINT ["python3", "-m", "janitor.git_store", "--port=9923", "--listen-address=0.0.0.0", "--vcs-path=/git"]
