FROM docker.io/debian:testing-slim AS m4
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        apt-file \
        aptitude \
        auto-apt-proxy \
        iproute2 \
 && apt-get clean \
 && apt-file update \
 && apt-file search /usr/share/aclocal/.*.m4 --regex -l | xargs aptitude -y install



FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update --yes \
 && apt-get install --yes --no-install-recommends \
        auto-apt-proxy \
        iproute2 \
 && apt-get upgrade --yes \
 && apt-get satisfy --yes --no-install-recommends \
       ## Standard packages
        ca-certificates \
        cargo \
       #gcc \
        git \
       #libclang-dev \
       #libgpgme-dev \
        libpython3-dev \
        libssl-dev \
        libtdb-dev \
        make \
       #mypy-protobuf \
        pkg-config \
        protobuf-compiler \
       #python3-gpg \
        python3-pip \
       #python3-setuptools \
       #python3-setuptools-rust \
       #python3-wheel \
       #python3-wheel-whl \
        rustc \
       #swig \
       ## Extra packages
        apt-file \
        autoconf \
        dpkg-dev \
        g++ \
        gnome-pkg-tools \
        libapt-pkg-dev \
 && apt-get clean \
 && apt-file update \
 && rm -rf /usr/share/aclocal

COPY --from=m4 /usr/share/aclocal /usr/share/aclocal

RUN pip3 install --break-system-packages --upgrade "python_apt@git+https://salsa.debian.org/apt-team/python-apt" \
 && git clone https://github.com/jelmer/ognibuild.git /build/ognibuild/ \
 && cd /build/ognibuild/ \
 && cargo build --verbose

EXPOSE 9934

ENTRYPOINT ["python3", "-m", "ognibuild.dep_server", "--port=9934", "--listen-address=0.0.0.0"]
