FROM ghcr.io/jelmer/janitor/base:latest
MAINTAINER Jelmer Vernooij <jelmer@debian.org>
EXPOSE 9912
RUN apt update && apt install --no-install-recommends -y python3-launchpadlib openssh-client gnupg
ENTRYPOINT ["python3", "-m", "janitor.publish", "--port=9912", "--listen-address=0.0.0.0"]
