FROM debian:sid-slim
MAINTAINER Jelmer Vernooij <jelmer@debian.org>
EXPOSE 9918
RUN apt -y update && apt -y --no-install-recommends install python3-slixmpp python3-aiohttp python3-aiohttp-openmetrics python3-pip && pip3 install google-cloud-logging
ADD notifiers /code/notifiers
ADD janitor_client /code/janitor_client
ENV PYTHONPATH=/code
ENTRYPOINT ["python3", "/code/notifiers/xmpp_notify.py", "--prometheus-port=9918", "--prometheus-listen-address=0.0.0.0"]
