FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive
RUN apt -y update && apt -y install --no-install-recommends auto-apt-proxy && apt -y upgrade && apt satisfy --no-install-recommends -y git cargo rustc libpython3-dev python3-wheel python3-wheel-whl make protobuf-compiler python3-setuptools python3-setuptools-rust ca-certificates python3-pip libgpgme-dev swig rustc cargo gcc mypy-protobuf libpcre3-dev python3-apt python3-gpg libssl-dev pkg-config openssh-client

COPY . /code
RUN pip3 install --break-system-packages /code[debian,gcp] && rm -rf /code
EXPOSE 9911
ENTRYPOINT ["python3", "-m", "janitor.runner", "--port=9911", "--listen-address=0.0.0.0"]
