FROM docker.io/debian:testing-slim AS build
MAINTAINER Jelmer Vernooij <jelmer@jelmer.uk>

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update \
 && apt-get -y install --no-install-recommends \
        auto-apt-proxy \
 && apt-get -y upgrade \
 && apt-get satisfy --no-install-recommends -y \
        ca-certificates \
        cargo \
        gcc \
        git \
        libclang-dev \
        libgpgme-dev \
        libpython3-dev \
        libssl-dev \
        libtdb-dev \
        make \
        mypy-protobuf \
        pkg-config \
        protobuf-compiler \
        python3-gpg \
        python3-pip \
        python3-setuptools \
        python3-setuptools-rust \
        python3-wheel \
        python3-wheel-whl \
        rustc \
        swig

COPY . /code

RUN pip3 install --break-system-packages --upgrade "/code[gcp]" \
 && rm -rf /code

EXPOSE 8082

# TODO: config
# TODO: service discovery
RUN apt-get update \
 && apt-get -y install --no-install-recommends \
        libjs-chart.js \
        libjs-jquery \
        libjs-jquery-datatables \
        libjs-jquery-typeahead \
        libjs-moment

ENTRYPOINT ["python3", "-m", "janitor.site.serve", "--port=8082", "--host=0.0.0.0"]
