[package]
name = "janitor-differ"
version = "0.0.0"
authors = ["Jelmer Vernooĳ <jelmer@jelmer.uk>"]
edition.workspace = true
description = "Differ for the janitor"
license = "GPL-3.0+"
repository = "https://github.com/jelmer/janitor.git"
homepage = "https://github.com/jelmer/janitor"

[dependencies]
janitor = { path = ".." }
clap = { optional = true, workspace = true }
env_logger = { optional = true, workspace = true }
serde_json.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing = "0.1.40"
serde.workspace = true
shlex.workspace = true
patchkit = "0.1.8"
axum.workspace = true
sqlx.workspace = true
redis = { workspace = true, features = ["aio", "connection-manager", "tokio", "tokio-comp", "json"] }
tempfile.workspace = true
breezyshim = { workspace = true, features = ["sqlx"] }
nix = { version = "0.29.0", features = ["resource"] }
axum-extra = { version = "0.9.6", features = ["typed-header"] }
headers = "0.4.0"
mime = "0.3.17"
accept-header = "0.2.3"
pyo3.workspace = true

[dev-dependencies]
maplit = { workspace = true }

[features]
cli = ["dep:clap", "dep:env_logger"]
default = ["cli"]

[[bin]]
name = "janitor-differ"
path = "src/main.rs"
required-features = ["cli"]
