from datetime import datetime
from typing import Optional

def calculate_next_try_time(finish_time: datetime, attempt_count: int) -> datetime: ...
def get_merged_by_user_url(url: str, user: str) -> Optional[str]: ...
