from datetime import datetime

def calculate_next_try_time(finish_time: datetime, attempt_count: int) -> datetime: ...
def get_merged_by_user_url(url: str, user: str) -> str | None: ...
def branches_match(url_a: str | None, url_b: str | None) -> bool: ...
