def find_dist_log_failure(
    logf: str, length: int
) -> tuple[int, tuple[int, int], list[int] | None]: ...
def find_build_log_failure(
    logf: str, length: int
) -> tuple[int, tuple[int, int], list[int] | None]: ...
