"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _BugTrackerKind:
    ValueType = typing.NewType('ValueType', builtins.int)
    V: typing_extensions.TypeAlias = ValueType
class _BugTrackerKindEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_BugTrackerKind.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    gitlab: _BugTrackerKind.ValueType  # 1
    debian: _BugTrackerKind.ValueType  # 2
    github: _BugTrackerKind.ValueType  # 3
class BugTrackerKind(_BugTrackerKind, metaclass=_BugTrackerKindEnumTypeWrapper):
    pass

gitlab: BugTrackerKind.ValueType  # 1
debian: BugTrackerKind.ValueType  # 2
github: BugTrackerKind.ValueType  # 3
global___BugTrackerKind = BugTrackerKind


class Distribution(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    ARCHIVE_MIRROR_URI_FIELD_NUMBER: builtins.int
    SIGNED_BY_FIELD_NUMBER: builtins.int
    CHROOT_FIELD_NUMBER: builtins.int
    CHROOT_ALIAS_FIELD_NUMBER: builtins.int
    COMPONENT_FIELD_NUMBER: builtins.int
    LINTIAN_PROFILE_FIELD_NUMBER: builtins.int
    LINTIAN_SUPPRESS_TAG_FIELD_NUMBER: builtins.int
    BUILD_COMMAND_FIELD_NUMBER: builtins.int
    VENDOR_FIELD_NUMBER: builtins.int
    EXTRA_FIELD_NUMBER: builtins.int
    name: typing.Text
    archive_mirror_uri: typing.Text
    signed_by: typing.Text
    chroot: typing.Text
    """Chroot name to use in sbuild"""

    @property
    def chroot_alias(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def component(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    lintian_profile: typing.Text
    @property
    def lintian_suppress_tag(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    build_command: typing.Text
    vendor: typing.Text
    @property
    def extra(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        archive_mirror_uri: typing.Optional[typing.Text] = ...,
        signed_by: typing.Optional[typing.Text] = ...,
        chroot: typing.Optional[typing.Text] = ...,
        chroot_alias: typing.Optional[typing.Iterable[typing.Text]] = ...,
        component: typing.Optional[typing.Iterable[typing.Text]] = ...,
        lintian_profile: typing.Optional[typing.Text] = ...,
        lintian_suppress_tag: typing.Optional[typing.Iterable[typing.Text]] = ...,
        build_command: typing.Optional[typing.Text] = ...,
        vendor: typing.Optional[typing.Text] = ...,
        extra: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["archive_mirror_uri",b"archive_mirror_uri","build_command",b"build_command","chroot",b"chroot","lintian_profile",b"lintian_profile","name",b"name","signed_by",b"signed_by","vendor",b"vendor"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["archive_mirror_uri",b"archive_mirror_uri","build_command",b"build_command","chroot",b"chroot","chroot_alias",b"chroot_alias","component",b"component","extra",b"extra","lintian_profile",b"lintian_profile","lintian_suppress_tag",b"lintian_suppress_tag","name",b"name","signed_by",b"signed_by","vendor",b"vendor"]) -> None: ...
global___Distribution = Distribution

class Config(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    LOGS_LOCATION_FIELD_NUMBER: builtins.int
    DATABASE_LOCATION_FIELD_NUMBER: builtins.int
    COMMITTER_FIELD_NUMBER: builtins.int
    DISTRIBUTION_FIELD_NUMBER: builtins.int
    ORIGIN_FIELD_NUMBER: builtins.int
    OAUTH2_PROVIDER_FIELD_NUMBER: builtins.int
    ARTIFACT_LOCATION_FIELD_NUMBER: builtins.int
    ZIPKIN_ADDRESS_FIELD_NUMBER: builtins.int
    CAMPAIGN_FIELD_NUMBER: builtins.int
    GIT_LOCATION_FIELD_NUMBER: builtins.int
    BZR_LOCATION_FIELD_NUMBER: builtins.int
    REDIS_LOCATION_FIELD_NUMBER: builtins.int
    USER_AGENT_FIELD_NUMBER: builtins.int
    BUGTRACKER_FIELD_NUMBER: builtins.int
    APT_REPOSITORY_FIELD_NUMBER: builtins.int
    logs_location: typing.Text
    """Location to store logs. Can either be a filesystem path or a http
    location, for use with GCS or S3.
    """

    database_location: typing.Text
    """postgresql URL for database connection"""

    committer: typing.Text
    """Default committer to use when committing changes."""

    @property
    def distribution(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Distribution]: ...
    origin: typing.Text
    """Origin in published archives"""

    @property
    def oauth2_provider(self) -> global___OAuth2Provider: ...
    artifact_location: typing.Text
    """Location to store build results"""

    zipkin_address: typing.Text
    """Location for zipkin server"""

    @property
    def campaign(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Campaign]: ...
    git_location: typing.Text
    """Location of git storage"""

    bzr_location: typing.Text
    """Location of bzr storage"""

    redis_location: typing.Text
    """Location of the redis server"""

    user_agent: typing.Text
    """User agent string"""

    @property
    def bugtracker(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BugTracker]: ...
    @property
    def apt_repository(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___AptRepository]: ...
    def __init__(self,
        *,
        logs_location: typing.Optional[typing.Text] = ...,
        database_location: typing.Optional[typing.Text] = ...,
        committer: typing.Optional[typing.Text] = ...,
        distribution: typing.Optional[typing.Iterable[global___Distribution]] = ...,
        origin: typing.Optional[typing.Text] = ...,
        oauth2_provider: typing.Optional[global___OAuth2Provider] = ...,
        artifact_location: typing.Optional[typing.Text] = ...,
        zipkin_address: typing.Optional[typing.Text] = ...,
        campaign: typing.Optional[typing.Iterable[global___Campaign]] = ...,
        git_location: typing.Optional[typing.Text] = ...,
        bzr_location: typing.Optional[typing.Text] = ...,
        redis_location: typing.Optional[typing.Text] = ...,
        user_agent: typing.Optional[typing.Text] = ...,
        bugtracker: typing.Optional[typing.Iterable[global___BugTracker]] = ...,
        apt_repository: typing.Optional[typing.Iterable[global___AptRepository]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["artifact_location",b"artifact_location","bzr_location",b"bzr_location","committer",b"committer","database_location",b"database_location","git_location",b"git_location","logs_location",b"logs_location","oauth2_provider",b"oauth2_provider","origin",b"origin","redis_location",b"redis_location","user_agent",b"user_agent","zipkin_address",b"zipkin_address"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["apt_repository",b"apt_repository","artifact_location",b"artifact_location","bugtracker",b"bugtracker","bzr_location",b"bzr_location","campaign",b"campaign","committer",b"committer","database_location",b"database_location","distribution",b"distribution","git_location",b"git_location","logs_location",b"logs_location","oauth2_provider",b"oauth2_provider","origin",b"origin","redis_location",b"redis_location","user_agent",b"user_agent","zipkin_address",b"zipkin_address"]) -> None: ...
global___Config = Config

class Env(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: typing.Text
    value: typing.Text
    def __init__(self,
        *,
        key: typing.Optional[typing.Text] = ...,
        value: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...
global___Env = Env

class MergeProposalConfig(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_THRESHOLD_FIELD_NUMBER: builtins.int
    COMMIT_MESSAGE_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    LABEL_FIELD_NUMBER: builtins.int
    value_threshold: builtins.int
    commit_message: typing.Text
    title: typing.Text
    @property
    def label(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        value_threshold: typing.Optional[builtins.int] = ...,
        commit_message: typing.Optional[typing.Text] = ...,
        title: typing.Optional[typing.Text] = ...,
        label: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["commit_message",b"commit_message","title",b"title","value_threshold",b"value_threshold"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["commit_message",b"commit_message","label",b"label","title",b"title","value_threshold",b"value_threshold"]) -> None: ...
global___MergeProposalConfig = MergeProposalConfig

class Campaign(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    BRANCH_NAME_FIELD_NUMBER: builtins.int
    MERGE_PROPOSAL_FIELD_NUMBER: builtins.int
    FORCE_BUILD_FIELD_NUMBER: builtins.int
    SKIP_SETUP_VALIDATION_FIELD_NUMBER: builtins.int
    DEFAULT_EMPTY_FIELD_NUMBER: builtins.int
    DEBIAN_BUILD_FIELD_NUMBER: builtins.int
    GENERIC_BUILD_FIELD_NUMBER: builtins.int
    BUGTRACKER_FIELD_NUMBER: builtins.int
    COMMAND_FIELD_NUMBER: builtins.int
    name: typing.Text
    """Name of the campaign. E.g. "lintian-fixes" """

    branch_name: typing.Text
    """VCS branch name to use"""

    @property
    def merge_proposal(self) -> global___MergeProposalConfig: ...
    force_build: builtins.bool
    """Force building even if the command did not make any changes."""

    skip_setup_validation: builtins.bool
    default_empty: builtins.bool
    @property
    def debian_build(self) -> global___DebianBuild: ...
    @property
    def generic_build(self) -> global___GenericBuild: ...
    @property
    def bugtracker(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BugTracker]: ...
    command: typing.Text
    """Default command, can be overridden on a per-package basis"""

    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        branch_name: typing.Optional[typing.Text] = ...,
        merge_proposal: typing.Optional[global___MergeProposalConfig] = ...,
        force_build: typing.Optional[builtins.bool] = ...,
        skip_setup_validation: typing.Optional[builtins.bool] = ...,
        default_empty: typing.Optional[builtins.bool] = ...,
        debian_build: typing.Optional[global___DebianBuild] = ...,
        generic_build: typing.Optional[global___GenericBuild] = ...,
        bugtracker: typing.Optional[typing.Iterable[global___BugTracker]] = ...,
        command: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["branch_name",b"branch_name","build",b"build","command",b"command","debian_build",b"debian_build","default_empty",b"default_empty","force_build",b"force_build","generic_build",b"generic_build","merge_proposal",b"merge_proposal","name",b"name","skip_setup_validation",b"skip_setup_validation"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["branch_name",b"branch_name","bugtracker",b"bugtracker","build",b"build","command",b"command","debian_build",b"debian_build","default_empty",b"default_empty","force_build",b"force_build","generic_build",b"generic_build","merge_proposal",b"merge_proposal","name",b"name","skip_setup_validation",b"skip_setup_validation"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["build",b"build"]) -> typing.Optional[typing_extensions.Literal["debian_build","generic_build"]]: ...
global___Campaign = Campaign

class GenericBuild(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CHROOT_FIELD_NUMBER: builtins.int
    chroot: typing.Text
    def __init__(self,
        *,
        chroot: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["chroot",b"chroot"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["chroot",b"chroot"]) -> None: ...
global___GenericBuild = GenericBuild

class DebianBuild(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    EXTRA_BUILD_DISTRIBUTION_FIELD_NUMBER: builtins.int
    BASE_DISTRIBUTION_FIELD_NUMBER: builtins.int
    CHROOT_FIELD_NUMBER: builtins.int
    BUILD_DISTRIBUTION_FIELD_NUMBER: builtins.int
    BUILD_SUFFIX_FIELD_NUMBER: builtins.int
    BUILD_COMMAND_FIELD_NUMBER: builtins.int
    @property
    def extra_build_distribution(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """Extra distributions to pull in packages from when building"""
        pass
    base_distribution: typing.Text
    chroot: typing.Text
    """Optional chroot, if different from that of base_distribution"""

    build_distribution: typing.Text
    """Distribution to target when building"""

    build_suffix: typing.Text
    """Suffix to add to version in changelog on build."""

    build_command: typing.Text
    def __init__(self,
        *,
        extra_build_distribution: typing.Optional[typing.Iterable[typing.Text]] = ...,
        base_distribution: typing.Optional[typing.Text] = ...,
        chroot: typing.Optional[typing.Text] = ...,
        build_distribution: typing.Optional[typing.Text] = ...,
        build_suffix: typing.Optional[typing.Text] = ...,
        build_command: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["base_distribution",b"base_distribution","build_command",b"build_command","build_distribution",b"build_distribution","build_suffix",b"build_suffix","chroot",b"chroot"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["base_distribution",b"base_distribution","build_command",b"build_command","build_distribution",b"build_distribution","build_suffix",b"build_suffix","chroot",b"chroot","extra_build_distribution",b"extra_build_distribution"]) -> None: ...
global___DebianBuild = DebianBuild

class OAuth2Provider(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CLIENT_ID_FIELD_NUMBER: builtins.int
    CLIENT_SECRET_FIELD_NUMBER: builtins.int
    BASE_URL_FIELD_NUMBER: builtins.int
    QA_REVIEWER_GROUP_FIELD_NUMBER: builtins.int
    ADMIN_GROUP_FIELD_NUMBER: builtins.int
    client_id: typing.Text
    client_secret: typing.Text
    base_url: typing.Text
    """A URL such as https://salsa.debian.org/
    Used for finding e.g. token and authorize URLs
    """

    qa_reviewer_group: typing.Text
    """Name of the OpenID group for QA reviewers"""

    admin_group: typing.Text
    """Name of the OpenID group for admins"""

    def __init__(self,
        *,
        client_id: typing.Optional[typing.Text] = ...,
        client_secret: typing.Optional[typing.Text] = ...,
        base_url: typing.Optional[typing.Text] = ...,
        qa_reviewer_group: typing.Optional[typing.Text] = ...,
        admin_group: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["admin_group",b"admin_group","base_url",b"base_url","client_id",b"client_id","client_secret",b"client_secret","qa_reviewer_group",b"qa_reviewer_group"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["admin_group",b"admin_group","base_url",b"base_url","client_id",b"client_id","client_secret",b"client_secret","qa_reviewer_group",b"qa_reviewer_group"]) -> None: ...
global___OAuth2Provider = OAuth2Provider

class BugTracker(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KIND_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    kind: global___BugTrackerKind.ValueType
    url: typing.Text
    """URL to the project in the bugtracker"""

    name: typing.Text
    def __init__(self,
        *,
        kind: typing.Optional[global___BugTrackerKind.ValueType] = ...,
        url: typing.Optional[typing.Text] = ...,
        name: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["kind",b"kind","name",b"name","url",b"url"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["kind",b"kind","name",b"name","url",b"url"]) -> None: ...
global___BugTracker = BugTracker

class Select(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    CAMPAIGN_FIELD_NUMBER: builtins.int
    campaign: typing.Text
    def __init__(self,
        *,
        campaign: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["campaign",b"campaign"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["campaign",b"campaign"]) -> None: ...
global___Select = Select

class AptRepository(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    NAME_FIELD_NUMBER: builtins.int
    BASE_FIELD_NUMBER: builtins.int
    SELECT_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    name: typing.Text
    base: typing.Text
    @property
    def select(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Select]: ...
    description: typing.Text
    """Human-readable description of the archive. Used in e.g. apt Release file."""

    def __init__(self,
        *,
        name: typing.Optional[typing.Text] = ...,
        base: typing.Optional[typing.Text] = ...,
        select: typing.Optional[typing.Iterable[global___Select]] = ...,
        description: typing.Optional[typing.Text] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["base",b"base","description",b"description","name",b"name"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["base",b"base","description",b"description","name",b"name","select",b"select"]) -> None: ...
global___AptRepository = AptRepository
