---
name: Build and Publish XMPP Notify Container

on:
  # run it on push to the default repository branch
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'  # Daily 6AM UTC build

jobs:
  # define job to build and publish container image
  build-and-push-xmpp-notify-container-image:
    name: Build container image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine tags to set (pull_request)
        run: |
          echo "TAGS=${{ github.sha }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'pull_request' }}

      - name: Determine tags to set (push)
        run: |
          echo "TAGS=${{ github.sha }} ${{ github.ref_name }}" >> $GITHUB_ENV
        if: ${{ github.event_name == 'push' }}

      - name: Login to Github Packages
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build xmpp-notify image
        id: build-image-xmpp-notify
        uses: redhat-actions/buildah-build@v2
        with:
          containerfiles: "Dockerfile_xmpp_notify"
          image: ghcr.io/jelmer/janitor/xmpp_notify
          tags: ${{ env.TAGS }}

      - name: Push xmpp-notify image to ghcr.io
        if: ${{ github.event_name != 'pull_request' }}
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image-xmpp-notify.outputs.image }}
          tags: ${{ steps.build-image-xmpp-notify.outputs.tags }}
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
