---
name: Build and Publish XMPP Notify Container

on:
  # run it on push to the default repository branch
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'  # Daily 6AM UTC build

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build xmpp-notify image
        uses: docker/build-push-action@v2
        with:
          file: "Dockerfile_xmpp_notify"
          tags: |
            ghcr.io/jelmer/janitor/xmpp_notify:${{ github.ref_name }}
            ghcr.io/jelmer/janitor/xmpp_notify:${{ github.sha }}
          push: ${{ github.event_name != 'pull_request' }}
