---
name: SQL

"on":
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'  # Daily 6AM UTC build

env:
  PG_MAJOR: "16"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          set -x
          sudo apt-get update --yes
          sudo apt-get satisfy --yes --no-install-recommends \
            postgresql-${PG_MAJOR} \
            postgresql-${PG_MAJOR}-debversion \
            postgresql-common \
      - name: Load SQL
        run: |
          set -x
          cat janitor/state.sql janitor/debian/debian.sql \
            | pg_virtualenv -v${PG_MAJOR} psql -v ON_ERROR_STOP=1
