---
name: SQL

"on":
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 6 * * *'  # Daily 6AM UTC build

env:
  PG_MAJOR: "14"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt install postgresql-${PG_MAJOR} postgresql-common \
            postgresql-${PG_MAJOR}-debversion
      - name: Load SQL
        run: |
          cat janitor/state.sql janitor/debian/debian.sql | \
            pg_virtualenv -v${PG_MAJOR} psql -v ON_ERROR_STOP=1
